class ACCUMULATE_METHODS:
    Execute = "execute"
    ExecuteAddCredits = "add-credits"
    ExecuteCreateAdi = "create-adi"
    ExecuteCreateDataAccount = "create-data-account"
    ExecuteCreateKeyBook = "create-key-book"
    ExecuteCreateKeyPage = "create-key-page"
    ExecuteCreateToken = "create-token"
    ExecuteCreateTokenAccount = "create-token-account"
    ExecuteSendTokens = "send-tokens"
    ExecuteUpdateKeyPage = "update-key-page"
    ExecuteWriteData = "write-data"
    Faucet = "faucet"
    Metrics = "metrics"
    Query = "query"
    QueryChain = "query-chain"
    QueryData = "query-data"
    QueryDataSet = "query-data-set"
    QueryDirectory = "query-directory"
    QueryKeyPageIndex = "query-key-index"
    QueryTx = "query-tx"
    QueryTxHistory = "query-tx-history"
    VERSION = "version"

class ACCUMULATE_TYPES:
    IDENTITY = "identity"
    LITE_TOKEN_ACCOUNT = "liteTokenAccount"
    VERSION = "version"
    KEY_PAGE = "keyPage"
    DATA_ENTRY = "dataEntry"
    KEY_PAGE_INDEX = "key-page-index"
    SYNTHETIC_DEPOSIT_TOKENS = "syntheticDepositTokens"
    METRICS = "metrics"
    DIRECTORY = "directory"
    DATASET = "dataSet"